### PR TITLE
Initial design changes

### PR DESCRIPTION
**Pull request by kermitauel**
screen shot 2015-04-23 at 2 39 31 pm
screen shot 2015-04-23 at 2 39 48 pm

### CODE REVIEW

**Comment by Gastove** [comment]
I'm not sure I'm equipped to be able to tell how amazing this is

**Comment by gmcquillan** [comment]
Monster Truck

**Comment by gmcquillan** [comment]
:rocket:
:sparkles:

**Comment by jarofghosts** [comment]
:boom: 
:bomb:

**Pull request merged**
